### ISSUE TITLE
Readability on grey or black backgrounds

### ISSUE THREAD

**Issue by buschtoens** [buschtoens/component-badge#1]
![example](http://f.cl.ly/items/1z2l1M090y0y372o0F0G/test.svg)

Maybe I should add a white background or dropshadow.

**Comment by ForbesLindesay** [comment]
Personally I prefer the transparent background, but I think it might be nice to replace the `scale` parameter with `options` and support `scale`, `background`, `subtitle-color` with defaults of `1`, `transparent` and `grey` respectively

**Comment by ForbesLindesay** [comment]
Maybe we could even have a complete inverse version of the image

**Comment by buschtoens** [comment]
Oh, that is a great idea!

**Comment by buschtoens** [comment]
Halfway done, don't start a PR or anything like that. Haha. :D

**Comment by buschtoens** [comment]
Done. I'll add some tests and then publish to npm.

**Comment by ForbesLindesay** [comment]
cool, I'm thinking that when we serve this image, we can provide support for options at some point in the future.

**Comment by buschtoens** [comment]
Published to npm.
